# Generated by Django 5.1.1 on 2024-10-08 03:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="EventTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("entry_time", models.TimeField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("section", models.CharField(max_length=100)),
                (
                    "session",
                    models.CharField(
                        choices=[
                            ("morning", "早場"),
                            ("afternoon", "午場"),
                            ("evening", "晚場"),
                        ],
                        max_length=10,
                    ),
                ),
                ("location_name", models.CharField(max_length=100)),
                ("location_address", models.CharField(max_length=200)),
                ("ticket_count", models.IntegerField()),
                ("dead_line_date", models.DateField()),
                ("dispatch_date", models.DateField()),
                ("announce_date", models.DateField()),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_times",
                        to="VIPSystem_APP.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StaffProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("@operation", "營運部"),
                            ("@lab", "服務科學實驗室"),
                            ("@ceoo", "執行長室"),
                            ("@bd", "商業開發事業部"),
                            ("@burn", "炎上"),
                            ("@tnns", "夜夜秀"),
                            ("@showcase", "拼盤秀"),
                            ("@stream", "串流"),
                            ("@agency", "藝人經紀"),
                            ("@so", "社群"),
                            ("@showdev", "節目開發"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VIP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("tags", models.ManyToManyField(blank=True, to="VIPSystem_APP.tag")),
            ],
        ),
        migrations.CreateModel(
            name="ProjectParticipation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("added", "已新增尚未寄信"),
                            ("confirmed", "確認參加"),
                            ("sended", "已發送邀請信件等待回覆"),
                            ("declined", "拒絕參加"),
                        ],
                        default="added",
                        max_length=20,
                    ),
                ),
                ("invited_at", models.DateTimeField(auto_now_add=True)),
                ("join_people_count", models.IntegerField(default=0)),
                (
                    "token",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "wish_attend",
                    models.CharField(blank=True, default="都可以", max_length=50),
                ),
                (
                    "wish_attend_section",
                    models.CharField(blank=True, default="台灣", max_length=50),
                ),
                (
                    "event_time",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="participations",
                        to="VIPSystem_APP.eventtime",
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vip_participations",
                        to="VIPSystem_APP.project",
                    ),
                ),
                (
                    "vip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_participations",
                        to="VIPSystem_APP.vip",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="project",
            name="participants",
            field=models.ManyToManyField(
                related_name="projects",
                through="VIPSystem_APP.ProjectParticipation",
                to="VIPSystem_APP.vip",
            ),
        ),
    ]
