# Generated by Django 5.1.1 on 2024-09-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("VIPSystem_APP", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectparticipation",
            name="status",
            field=models.CharField(
                choices=[
                    ("added", "已新增尚未寄信"),
                    ("confirmed", "確認參加"),
                    ("sended", "已發送邀請信件等待回覆"),
                    ("declined", "拒絕參加"),
                ],
                default="added",
                max_length=20,
            ),
        ),
    ]
