# Generated by Django 5.1.1 on 2024-10-08 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("VIPSystem_APP", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectparticipation",
            name="last_update_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
