# Generated by Django 5.1.1 on 2024-09-12 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("VIPSystem_APP", "0002_tag_vip_phone_number_vip_tags"),
        ("socialaccount", "0006_alter_socialaccount_extra_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomSocialApp",
            fields=[],
            options={"proxy": True, "indexes": [], "constraints": [],},
            bases=("socialaccount.socialapp",),
        ),
    ]
