# Generated by Django 5.1.1 on 2024-12-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("VIPSystem_APP", "0002_projectparticipation_last_update_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectparticipation",
            name="wish_attend",
            field=models.CharField(blank=True, default="all", max_length=50),
        ),
        migrations.AlterField(
            model_name="projectparticipation",
            name="wish_attend_section",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
