# Generated by Django 5.1.1 on 2024-09-18 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("VIPSystem_APP", "0003_customsocialapp"),
    ]

    operations = [
        migrations.DeleteModel(name="CustomSocialApp",),
    ]
