# Generated by Django 5.1.1 on 2024-12-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("VIPSystem_APP", "0003_alter_projectparticipation_wish_attend_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectparticipation",
            name="wish_ticket_count",
            field=models.IntegerField(default=2),
        ),
    ]
