# Generated by Django 5.1.1 on 2024-09-24 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("VIPSystem_APP", "0003_projectparticipation_join_people_count_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="project", name="end_date",),
        migrations.RemoveField(model_name="project", name="start_date",),
        migrations.CreateModel(
            name="EventTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                (
                    "session",
                    models.CharField(
                        choices=[
                            ("morning", "早場"),
                            ("afternoon", "午場"),
                            ("evening", "晚場"),
                        ],
                        max_length=10,
                    ),
                ),
                ("location", models.CharField(max_length=100)),
                ("ticket_count", models.IntegerField()),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_times",
                        to="VIPSystem_APP.project",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="projectparticipation",
            name="event_time",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="participations",
                to="VIPSystem_APP.eventtime",
            ),
        ),
    ]
