# Generated by Django 5.1.1 on 2024-09-25 02:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "VIPSystem_APP",
            "0004_remove_project_end_date_remove_project_start_date_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="eventtime", old_name="time", new_name="end_time",
        ),
        migrations.RenameField(
            model_name="eventtime", old_name="location", new_name="location_name",
        ),
        migrations.AddField(
            model_name="eventtime",
            name="location_address",
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="eventtime",
            name="start_time",
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
