# Generated by Django 5.1.1 on 2024-12-17 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("VIPSystem_APP", "0004_projectparticipation_wish_ticket_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventtime",
            name="session",
            field=models.CharField(max_length=20),
        ),
    ]
