# Generated by Django 5.1.1 on 2024-12-17 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("VIPSystem_APP", "0005_alter_eventtime_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="vip",
            name="address",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="vip",
            name="nickname",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="vip", name="notes", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="vip",
            name="organization",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="vip",
            name="poc",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="vip",
            name="poc_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="vip",
            name="poc_phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="vip",
            name="poc_position",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="vip",
            name="position",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="vip",
            name="str_connect",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="vip",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
