# Generated by Django 5.1.1 on 2024-09-18 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("VIPSystem_APP", "0005_projectparticipation"),
    ]

    operations = [
        migrations.DeleteModel(name="ProjectParticipation",),
    ]
