# Generated by Django 5.1.1 on 2024-10-01 15:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("VIPSystem_APP", "0005_rename_time_eventtime_end_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventtime",
            name="announce_date",
            field=models.DateField(default='2004-11-12'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="eventtime",
            name="dead_line_date",
            field=models.DateField(default='2004-11-12'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="eventtime",
            name="dispatch_date",
            field=models.DateField(default='2004-11-12'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="eventtime",
            name="entry_time",
            field=models.TimeField(null=True, blank=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="eventtime",
            name="section",
            field=models.CharField(default="台北", max_length=100),
            preserve_default=False,
        ),
    ]
