# Generated by Django 5.1.1 on 2024-12-17 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "VIPSystem_APP",
            "0006_vip_address_vip_nickname_vip_notes_vip_organization_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="EventTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticket_count", models.IntegerField(default=0)),
                (
                    "event_time",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_tickets",
                        to="VIPSystem_APP.eventtime",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_tickets",
                        to="VIPSystem_APP.staffprofile",
                    ),
                ),
            ],
            options={"unique_together": {("staff", "event_time")},},
        ),
    ]
