# Generated by Django 5.1.1 on 2024-10-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "VIPSystem_APP",
            "0006_eventtime_announce_date_eventtime_dead_line_date_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="projectparticipation",
            name="wish_attend",
            field=models.CharField(blank=True, default="都可以", max_length=50),
        )
    ]
