# Generated by Django 5.1.1 on 2024-10-04 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("VIPSystem_APP", "0007_projectparticipation_wish_attend_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectparticipation",
            name="wish_attend_section",
            field=models.CharField(blank=True, default="台灣", max_length=50),
        )
    ]
