# Generated by Django 5.1.1 on 2024-12-24 03:05

from django.db import migrations, models  # 注意這裡添加了 models

def initialize_sequence_numbers(apps, schema_editor):
    ProjectParticipation = apps.get_model('VIPSystem_APP', 'ProjectParticipation')
    Project = apps.get_model('VIPSystem_APP', 'Project')
    
    # 獲取所有專案
    projects = Project.objects.all()
    
    for project in projects:
        # 獲取該專案的所有參與記錄，按創建時間排序
        participations = ProjectParticipation.objects.filter(
            project=project
        ).order_by('invited_at')
        
        # 為每個參與記錄設置序號
        for index, participation in enumerate(participations, start=1):
            participation.pp_id = index
            participation.save(update_fields=['pp_id'])

class Migration(migrations.Migration):
    dependencies = [
        ('VIPSystem_APP', '0008_alter_eventtime_options_and_more'),  # 確保這是你的前一個遷移文件名
    ]

    operations = [
        migrations.AddField(
            model_name='projectparticipation',
            name='pp_id',
            field=models.IntegerField(null=True),  # 使用 models.IntegerField
        ),
        migrations.RunPython(
            initialize_sequence_numbers,
            reverse_code=migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name='projectparticipation',
            name='pp_id',
            field=models.IntegerField(),  # 使用 models.IntegerField
        ),
    ]