# Generated by Django 5.1.1 on 2024-12-24 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("VIPSystem_APP", "0009_add_sequence_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectparticipation",
            name="pp_id",
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name="projectparticipation",
            name="status",
            field=models.CharField(
                choices=[
                    ("added", "尚未寄出邀請信"),
                    ("confirmed", "確認參加"),
                    ("sended", "已發送邀請信件等待回覆"),
                    ("declined", "拒絕參加"),
                ],
                default="added",
                max_length=20,
            ),
        ),
    ]
