# Generated by Django 5.1.1 on 2024-12-25 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("VIPSystem_APP", "0010_alter_projectparticipation_pp_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectparticipation",
            name="notes",
            field=models.TextField(blank=True),
        ),
    ]
