# Generated by Django 5.1.1 on 2024-12-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("VIPSystem_APP", "0012_projectparticipation_send_check_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffprofile",
            name="nickname",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
