# Generated by Django 5.1.1 on 2025-01-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VIPSystem_APP', '0013_staffprofile_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectparticipation',
            name='get_ticket_check',
            field=models.BooleanField(default=False),
        ),
    ]
