# Generated by Django 5.1.1 on 2025-01-13 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VIPSystem_APP', '0014_projectparticipation_get_ticket_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectparticipation',
            name='seat_number',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
